import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { spawnSync } from "node:child_process";

interface CommandRecord {
  command: string;
  args: string[];
  exitCode: number;
  stdoutTail: string;
  stderrTail: string;
}

const root = resolve(new URL("..", import.meta.url).pathname);
const args = process.argv.slice(2);
const outputIndex = args.indexOf("--output");
const outputPath =
  outputIndex >= 0 && args[outputIndex + 1]
    ? resolve(args[outputIndex + 1])
    : null;

function run(command: string, commandArgs: string[]): CommandRecord {
  const result = spawnSync(command, commandArgs, {
    cwd: root,
    encoding: "utf8",
    shell: process.platform === "win32",
    env: { ...process.env, CI: "1" },
    maxBuffer: 32 * 1024 * 1024,
  });
  const stdout = result.stdout ?? "";
  const stderr = result.stderr ?? "";
  const record: CommandRecord = {
    command,
    args: [...commandArgs],
    exitCode: result.status ?? 1,
    stdoutTail: stdout.slice(-8_000),
    stderrTail: stderr.slice(-8_000),
  };
  if (record.exitCode !== 0) {
    console.error(JSON.stringify({ status: "FAILED", failed: record }, null, 2));
    process.exit(record.exitCode || 1);
  }
  return record;
}

function readGitHead(): string {
  const result = spawnSync("git", ["rev-parse", "HEAD"], {
    cwd: root,
    encoding: "utf8",
    shell: process.platform === "win32",
  });
  if (result.status !== 0) throw new Error(`git rev-parse failed: ${result.stderr}`);
  return result.stdout.trim();
}

async function sha256File(path: string): Promise<{ path: string; bytes: number; sha256: string }> {
  const bytes = await readFile(resolve(root, path));
  return {
    path,
    bytes: bytes.length,
    sha256: createHash("sha256").update(bytes).digest("hex"),
  };
}

const commands: Array<[string, string[]]> = [
  ["npm", ["run", "verify"]],
  ["npm", ["run", "research:benchmark:write"]],
  ["npm", ["run", "statistics:family:write"]],
  ["npm", ["run", "certificate:v2:write"]],
  [
    "npm",
    [
      "run",
      "verify:certificate",
      "--",
      "data/certificates/canonical-v2.json",
    ],
  ],
];

const records = commands.map(([command, commandArgs]) => run(command, commandArgs));
const artifacts = await Promise.all(
  [
    "data/benchmarks/reconciliation-results.json",
    "data/analysis/canonical-family-inference.json",
    "data/certificates/canonical-v2.json",
    "package-lock.json",
  ].map(sha256File)
);

const report = {
  kind: "MPWResearchReproductionReport",
  schemaVersion: 1,
  repositoryHead: readGitHead(),
  environment: {
    node: process.version,
    platform: process.platform,
    architecture: process.arch,
  },
  commands: records,
  artifacts,
  status: "PASS",
  interpretation: [
    "PASS means every listed command exited zero in this recorded environment.",
    "Artifact hashes bind generated bytes to this report but do not authenticate publishers or establish scientific truth.",
    "Environment metadata is intentionally descriptive and may differ across successful reproductions.",
  ],
};

if (outputPath) {
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, `${JSON.stringify(report, null, 2)}\n`, "utf8");
}
console.log(JSON.stringify(report, null, 2));
